package fg.elements

open class Article() : Element(name = "article")
open class Section() : Element(name = "section")
open class Nav() : Element(name = "nav")
open class Aside() : Element(name = "aside")
open class H1() : Element(name = "h1")
open class H2() : Element(name = "h2")
open class H3() : Element(name = "h3")
open class H4() : Element(name = "h4")
open class H5() : Element(name = "h5")
open class H6() : Element(name = "h6")
open class Header() : Element(name = "header")
open class Footer() : Element(name = "footer")
open class Address() : Element(name = "address")
